name: nightly
on:
  push:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      commit: master

  tests:
    needs: build
    uses: ./.github/workflows/tests.yml
    with:
      event: ${{ github.event_name }}

  clean:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
