name: tests
on:
  workflow_call:
    inputs:
      event:
        type: string
        default: "push"

jobs:
  test-linux:
    if: false
    runs-on: ubuntu-latest
    container:
      image: rbernon/winehq:stable
      options: --user root
    strategy:
      matrix:
        arch: [win32, win64]
        test: [nulldrv, desktop, fvwm, openbox, kwin, mutter, modeset, wayland, vulkan]
        include:
          - arch: wow64
            test: fvwm
          - arch: wow64
            test: vulkan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        if: ${{ matrix.arch == 'wow64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-win64

      - name: Download
        if: ${{ matrix.arch != 'wow64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-${{ matrix.arch }}

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          useradd github && mkdir -p /home/github /home/github/Documents /home/github/Desktop && chown github:github -R /home/github
          su - github $PWD/test-linux $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-linux-${{ matrix.test }}-${{ matrix.arch }}.report
          path: /home/github/*.report

  test-linux-trixie:
    if: false
    runs-on: ubuntu-latest
    container:
      image: rbernon/winehq:trixie
      options: --user root
    strategy:
      matrix:
        arch: [win32, win64]
        test: [trixie]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        if: ${{ matrix.arch == 'wow64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-win64

      - name: Download
        if: ${{ matrix.arch != 'wow64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-${{ matrix.arch }}

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          useradd github && mkdir -p /home/github /home/github/Documents /home/github/Desktop && chown github:github -R /home/github
          su - github $PWD/test-linux $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-linux-${{ matrix.test }}-${{ matrix.arch }}.report
          path: /home/github/*.report

  test-macos:
    if: false
    runs-on: macos-13
    strategy:
      matrix:
        arch: [win64]
        test: [opengl, vulkan]
        include:
          - arch: wow64
            test: opengl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-macos-${{ matrix.test }}-${{ matrix.arch }}.report
          path: macos-*.report

  test-macos-m1ros2:
    if: false
    runs-on: macos-14
    strategy:
      matrix:
        arch: [win64, wow64]
        test: [m1ros2-vulkan]
        include:
          - arch: wow64
            test: m1ros2-opengl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Test
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          eval "$(/usr/local/bin/brew shellenv)"
          arch -x86_64 brew install --overwrite python

          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          arch -x86_64 $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: test-macos-${{ matrix.test }}-${{ matrix.arch }}.report
          path: m1ros2-*.report

  test-windows:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - run: |
          gh -R rbernon/winetest-w7e        workflow run windows -f run_id=${{ github.run_id }} -f event=${{ inputs.event }} -f install=7e   -f version=w7e64 ||:
          gh -R rbernon/winetest-w81e       workflow run windows -f run_id=${{ github.run_id }} -f event=${{ inputs.event }} -f install=81e  -f version=w81e64 ||:
          gh -R rbernon/winetest-w10pro     workflow run windows -f run_id=${{ github.run_id }} -f event=${{ inputs.event }} -f install=10   -f version=w10pro64 ||:
          gh -R rbernon/winetest-w10ltsc    workflow run windows -f run_id=${{ github.run_id }} -f event=${{ inputs.event }} -f install=10l  -f version=w10ltsc64 ||:
          gh -R rbernon/winetest-w11pro     workflow run windows -f run_id=${{ github.run_id }} -f event=${{ inputs.event }} -f install=11   -f version=w11pro64 ||:
          gh -R rbernon/winetest-w11ltsc    workflow run windows -f run_id=${{ github.run_id }} -f event=${{ inputs.event }} -f install=11l  -f version=w11ltsc64 ||:
